### PR TITLE
Add authorship attribution on post pages

### PR DESCRIPTION
**Pull request by HeroicEric**
Adds a link to author's twitter on the post page.

Looks like:

screen shot 2015-01-28 at 12 58 48 pm

We can get more detailed with photos etc but this sets up all the plumbing for for now.

### CODE REVIEW

**Comment by davekaro** [comment]
Why link to Twitter?

**Comment by HeroicEric** [comment]
No reason really. Everybody's data is in a .yml file, so we could just make it link to wherever you want if we give everybody a `web_link` key or something.

**Comment by davekaro** [comment]
yup. This is great for now. Eventually maybe each author gets their own page with their posts.

**Comment by mikepmunroe** [comment]
Dave, great idea for future enhancement. Will merge Eric's start in the right direction for now.

**Comment by rtremaine** [comment]
sweet!!

**Pull request merged**
